### ISSUE TITLE
Remove ground_speed requirement in getEdges

### ISSUE THREAD

**Issue by kaijagahm** [kaijagahm/vultureUtils#104]
Should only require a speed column if filtering is going to be done by speed. And user should be able to specify the name of the column. NULL should be the default and that should be fine.

Should also have an explicit null default for roostPolygons.

**Comment by ryannguyen6392** [comment]
Leaving the name of the column (speedCol) to default to NULL throws an error when passed to filterLocs.
I think this is because filterLocs can't default to "ground_speed", which is the name of the column in the testing dataset, when passed NULL as for its speedCol value.

As a fix, speedCol also defaults to "ground_speed", but can now be used by the user in getEdges.
(Note: this might be a good place to use the ... operator to optionally pass speedCol)

roostPolygons is now explicitly defaulted to NULL
